# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'census_datavault'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'census_datavault'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models", "models/refined", "models/report", "models/stage"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  census_datavault:
    stage:
      +schema: "stage"
      +materialized: table
    refined:
      +schema: "refined"
      +materialized: table
      hub_year:
        +materialized: table
      hub_geo:
        +materialized: table
      hub_var:
        +materialized: table
      link_year_geo_var:
        +materialized: table
      sat_geo:
        +materialized: table
      sat_var:
        +materialized: table
      sat_year_geo_var:
        +materialized: table
    report:
      +schema: "report"
      +materialized: table
      pop_pyr:
        +materialized: table
      ratios:
        +materialized: table
      central_measures:
        +materialized: table
      total_pop:
        +materialized: table
